version: '3.8'
services:
  flask_app:
    build: ./flask_app
    ports:
      - "5000:5000"
    depends_on:
      - mysql_db
    environment:
      - MYSQL_HOST=mysql_db
      - MYSQL_USER=sora
      - MYSQL_PASSWORD=sora
      - MYSQL_DB=videolinks
    volumes:
      - ./flask_app:/usr/src/app
  mysql_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: sora
      MYSQL_DATABASE: videolinks
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
