version: "3.8"

services:
  authentication:
    image: soranosuke/authentication:latest
    ports:
      - "8090:8090"
    networks:
      - acit3495projectnetwork

  mysql:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=videos
      - MYSQL_USER=sora
      - MYSQL_PASSWORD=sora
    ports:
      - "3306:3306"
    networks:
      - acit3495projectnetwork
    volumes:
      - mysql-data:/var/lib/mysql

  db_app:
    image: soranosuke/db_app:latest
    ports:
      - "8100:8100"
    networks:
      - acit3495projectnetwork
    depends_on:
      mysql:
        condition: service_started

  file-manager:
    image: soranosuke/file_manager:latest
    ports:
      - "8080:8080"
    networks:
      - acit3495projectnetwork

  upload-video:
    image: soranosuke/upload_video:latest
    ports:
      - "8200:8200"
    networks:
      - acit3495projectnetwork

  video-streaming:
    image: soranosuke/video_streaming:latest
    ports:
      - "3000:3000"
    networks:
      - acit3495projectnetwork

networks:
  acit3495projectnetwork:
    driver: bridge

volumes:
  mysql-data:
