apiVersion: apps/v1
kind: Deployment
metadata:
  name: db-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-app
  template:
    metadata:
      labels:
        app: db-app
    spec:
      containers:
      - name: db-app
        image: us-west1-docker.pkg.dev/acit-3855-vm/video-streaming-service/db_app:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8100
---
apiVersion: v1
kind: Service
metadata:
  name: db-app-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8100
  selector:
    app: db-app
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: db-app-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: db-app
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
