apiVersion: apps/v1
kind: Deployment
metadata:
  name: file-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: file-manager
  template:
    metadata:
      labels:
        app: file-manager
    spec:
      containers:
      - name: file-manager
        image: us-west1-docker.pkg.dev/acit-3855-vm/video-streaming-service/file_manager:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: file-manager-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: file-manager
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: file-manager-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: file-manager
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
