apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-video
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-video
  template:
    metadata:
      labels:
        app: upload-video
    spec:
      containers:
      - name: upload-video
        image: soranosuke/upload_video:latest
        ports:
        - containerPort: 8200
---
apiVersion: v1
kind: Service
metadata:
  name: upload-video-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8200
  selector:
    app: upload-video
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: upload-video-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: upload-video
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 50
